### ISSUE TITLE
No repo license/description causes a `TypeError`

### ISSUE THREAD

**Issue by tnahs** [Justintime50/homebrew-releaser#17]
I build this off a test repo so there were some things missing. I noticed that the action crashes if the repo is missing a description or a license. Usually these would be set on a non-test repo but it might be good to either document the requirements, have a default fallback or allow the user to set these in the workflow, especially description.

Having no license set causes a `TypeError` error.

```plaintext
Traceback (most recent call last):
  File "/homebrew_releaser/app.py", line 197, in <module>
    main()
  File "/homebrew_releaser/app.py", line 193, in main
    App.run_github_action()
  File "/homebrew_releaser/app.py", line 121, in run_github_action
    template = Formula.generate_formula_data(
  File "/homebrew_releaser/formula.py", line 45, in generate_formula_data
    license_type = repository['license']['spdx_id']
TypeError: 'NoneType' object is not subscriptable
```

Having no description set causes a `TypeError` error.

```plantext
Traceback (most recent call last):
  File "/homebrew_releaser/app.py", line 197, in <module>
    main()
  File "/homebrew_releaser/app.py", line 193, in main
    App.run_github_action()
  File "/homebrew_releaser/app.py", line 121, in run_github_action
    template = Formula.generate_formula_data(
  File "/homebrew_releaser/formula.py", line 46, in generate_formula_data
    description = re.sub(r'[.!]+', '', repository['description'][:max_desc_field_length]).strip().capitalize()
TypeError: 'NoneType' object is not subscriptable
```

Thanks!

**Comment by Justintime50** [comment]
Fixed via https://github.com/Justintime50/homebrew-releaser/commit/730005e8f80f4309d9f7620a1733deae1d8cc68d

**Comment by tnahs** [comment]
Thanks! 🎉
